<?php

use yii\db\Migration;

class m221105_101636_bloc extends Migration
{
    public function up()
    {
        /* 取消外键约束 */
        $this->execute('SET foreign_key_checks = 0');
        
        /* 创建表 */
        $this->createTable('{{%bloc}}', [
            'bloc_id' => "int(10) unsigned NOT NULL AUTO_INCREMENT",
            'invitation_code' => "varchar(50) NULL COMMENT '邀请码'",
            'business_name' => "varchar(50) NOT NULL COMMENT '公司名称'",
            'pid' => "int(11) NULL DEFAULT '0' COMMENT '上级商户'",
            'group_bloc_id' => "int(11) NULL DEFAULT '0' COMMENT '集团ID'",
            'category' => "varchar(255) NULL DEFAULT '0'",
            'province' => "varchar(15) NULL COMMENT '省份'",
            'city' => "varchar(15) NULL COMMENT '城市'",
            'district' => "varchar(15) NULL COMMENT '区县'",
            'address' => "varchar(50) NULL COMMENT '具体地址'",
            'register_level' => "int(11) NULL COMMENT '注册级别'",
            'longitude' => "varchar(15) NULL COMMENT '经度'",
            'latitude' => "varchar(15) NULL COMMENT '纬度'",
            'telephone' => "varchar(20) NULL COMMENT '电话'",
            'avg_price' => "int(10) unsigned NULL",
            'recommend' => "varchar(255) NULL COMMENT '介绍'",
            'special' => "varchar(255) NULL COMMENT '特色'",
            'introduction' => "varchar(255) NULL COMMENT '详细介绍'",
            'open_time' => "varchar(50) NULL COMMENT '开业时间'",
            'status' => "tinyint(3) unsigned NULL DEFAULT '0' COMMENT '0 待审核 1 审核通过 2 审核未通过'",
            'is_group' => "tinyint(3) NULL DEFAULT '0' COMMENT '是否是集团'",
            'sosomap_poi_uid' => "varchar(50) NULL DEFAULT '' COMMENT '腾讯地图标注id'",
            'license_no' => "varchar(30) NULL DEFAULT '' COMMENT '营业执照注册号或组织机构代码'",
            'license_name' => "varchar(100) NULL DEFAULT '' COMMENT '营业执照名称'",
            'level_num' => "int(11) NULL COMMENT '等级'",
            'store_id' => "int(11) NULL DEFAULT '0'",
            'other_files' => "text NULL COMMENT '其他文件'",
            'extra' => "text NULL COMMENT '我的家族'",
            'PRIMARY KEY (`bloc_id`)'
        ], "ENGINE=InnoDB  DEFAULT CHARSET=utf8");
        
        /* 索引设置 */
        
        
        /* 表数据 */
        $this->insert('{{%bloc}}',['bloc_id'=>'8','invitation_code'=>NULL,'business_name'=>'店滴','pid'=>'0','group_bloc_id'=>'8','category'=>'0','province'=>'2367','city'=>'2368','district'=>'2373','address'=>'4536','register_level'=>'0','longitude'=>'456','latitude'=>'567','telephone'=>'5676575','avg_price'=>'20','recommend'=>'34','special'=>'乐乐巴布','introduction'=>'234535','open_time'=>'234','status'=>'0','is_group'=>'1','sosomap_poi_uid'=>'','license_no'=>'23425','license_name'=>'5467','level_num'=>NULL,'store_id'=>'61','other_files'=>NULL,'extra'=>'s:48:"s:40:"s:32:"s:24:"s:16:"s:9:"s:2:"N;";";";";";";";']);
        $this->insert('{{%bloc}}',['bloc_id'=>'12','invitation_code'=>NULL,'business_name'=>'客户演示','pid'=>'8','group_bloc_id'=>'8','category'=>'0','province'=>'801','city'=>'802','district'=>'806','address'=>'3243','register_level'=>'0','longitude'=>'3435','latitude'=>'45','telephone'=>'5656','avg_price'=>'10','recommend'=>'2112','special'=>'4345','introduction'=>'3434','open_time'=>'23','status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'343','license_name'=>'56','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'13','invitation_code'=>NULL,'business_name'=>'西安店滴云网络科技有限公司','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'37','city'=>'197','district'=>'205','address'=>'西安软件园东区汉韵阁-A座','register_level'=>'1','longitude'=>'108.888941','latitude'=>'34.229398','telephone'=>'17778984690','avg_price'=>'1','recommend'=>'2','special'=>'23','introduction'=>'12','open_time'=>'1656950400','status'=>'1','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'12','license_name'=>'23','level_num'=>'2','store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'14','invitation_code'=>'62qNQ','business_name'=>'智能手表','pid'=>'8','group_bloc_id'=>'0','category'=>'0','province'=>'801','city'=>'802','district'=>'813','address'=>'钟楼','register_level'=>'0','longitude'=>'116.39039','latitude'=>'39.872394','telephone'=>'17778984690','avg_price'=>'23','recommend'=>'43','special'=>'23','introduction'=>'45','open_time'=>'1664380800','status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'56','license_name'=>'西安店滴云网络科技有限公司','level_num'=>'2','store_id'=>'0','other_files'=>'','extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'16','invitation_code'=>'e2dX2','business_name'=>'智能手表','pid'=>NULL,'group_bloc_id'=>'0','category'=>'0','province'=>'801','city'=>'802','district'=>'813','address'=>'西安','register_level'=>'0','longitude'=>'116.371418','latitude'=>'39.859546','telephone'=>'17778984690','avg_price'=>'23','recommend'=>'34','special'=>'23','introduction'=>'233232','open_time'=>'1664380800','status'=>'1','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'12','license_name'=>'32','level_num'=>'2','store_id'=>'0','other_files'=>'','extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'17','invitation_code'=>'Zx8Lx','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'18','invitation_code'=>'zxgY2','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'19','invitation_code'=>'ZxJNx','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'20','invitation_code'=>'oxa8Q','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'21','invitation_code'=>'o2RgQ','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'22','invitation_code'=>'dwDjQ','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'23','invitation_code'=>'LQ1ow','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'24','invitation_code'=>'V2k8Q','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'25','invitation_code'=>'jwy9w','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'26','invitation_code'=>'dxozQ','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'27','invitation_code'=>'q2P02','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'28','invitation_code'=>'LxAg2','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'29','invitation_code'=>'AwE1w','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'30','invitation_code'=>'V29gx','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'31','invitation_code'=>'7x6aQ','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'32','invitation_code'=>'VwZ9x','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'33','invitation_code'=>'bx4Lx','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'34','invitation_code'=>'7x3nQ','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'35','invitation_code'=>'LwKYQ','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'36','invitation_code'=>'jQX6w','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'37','invitation_code'=>'5x0V2','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'38','invitation_code'=>'o2edw','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'39','invitation_code'=>'yxjl2','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'40','invitation_code'=>'jQp5x','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'41','invitation_code'=>'p2rdx','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'42','invitation_code'=>'rxOgx','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'43','invitation_code'=>'yw7kw','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'44','invitation_code'=>'QLaqx','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'45','invitation_code'=>'2NYYw','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        $this->insert('{{%bloc}}',['bloc_id'=>'46','invitation_code'=>'Qnez2','business_name'=>'您的公司名称','pid'=>'0','group_bloc_id'=>'0','category'=>'0','province'=>'0','city'=>'0','district'=>'0','address'=>'','register_level'=>'0','longitude'=>'','latitude'=>'','telephone'=>NULL,'avg_price'=>NULL,'recommend'=>NULL,'special'=>NULL,'introduction'=>NULL,'open_time'=>NULL,'status'=>'0','is_group'=>'0','sosomap_poi_uid'=>'','license_no'=>'','license_name'=>'','level_num'=>NULL,'store_id'=>'0','other_files'=>NULL,'extra'=>NULL]);
        
        /* 设置外键约束 */
        $this->execute('SET foreign_key_checks = 1;');
    }

    public function down()
    {
        $this->execute('SET foreign_key_checks = 0');
        /* 删除表 */
        $this->dropTable('{{%bloc}}');
        $this->execute('SET foreign_key_checks = 1;');
    }
}

