#!/usr/bin/env php
<?php
/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2021-01-19 20:26:00
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2022-09-01 20:16:41
 */
defined('COROUTINE_ENV') or define('COROUTINE_ENV', true);

use diandi\swoole\websocket\server\WebSocketServer;
use Swoole\Runtime;

\Co::set(['hook_flags'=> SWOOLE_HOOK_ALL]);
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', getenv('PHP_ENV') === 'development' ? 'dev' : 'prod');

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/vendor/yiisoft/yii2/Yii.php';

// $config = require __DIR__.'/config/websocket.php';
$config = yii\helpers\ArrayHelper::merge(
    [
        'app'=>[
            'params'=> yii\helpers\ArrayHelper::merge(
                require(__DIR__ . '/common/config/params.php'),
                require(__DIR__ . '/common/config/params-local.php'),
            )
        ]
    ],
    require __DIR__ . '/swoole/config/websocket.php'
);
$server = new WebSocketServer($config);
$server->run();
