<?php
/**
 * @Author: Wang chunsheng  email:2192138785@qq.com
 * @Date:   2022-07-18 09:49:23
 * @Last Modified by:   Wang chunsheng  email:2192138785@qq.com
 * @Last Modified time: 2022-08-01 09:43:20
 */
 return array (
  0 => 
  array (
    'name' => '媒体',
    'route' => '/diandi_website/ad/index',
    'order' => 2,
    'data' => NULL,
    'type' => '',
    'level_type' => 1,
    'icon' => 'fa fa-caret-square-o-right',
    'is_sys' => 'addons',
    'module_name' => 'diandi_website',
    'is_show' => 0,
    'ruoter' => 
    array (
      'name' => '/diandi_website/ad/index',
      'item_id' => 13273,
      'route_name' => 'diandi-website-ad-index',
      'is_sys' => 0,
      'route_type' => 0,
      'description' => NULL,
      'title' => NULL,
      'pid' => 0,
      'data' => NULL,
      'module_name' => 'diandi_website',
      'item' => 
      array (
        'name' => 'diandi-website-ad-index',
        'is_sys' => 0,
        'permission_type' => 0,
        'description' => NULL,
        'rule_name' => 0,
        'parent_id' => 0,
        'permission_level' => 0,
        'data' => NULL,
        'module_name' => 'diandi_website',
      ),
    ),
    'level' => 3,
    'child' => 
    array (
      0 => 
      array (
        'name' => '广告',
        'route' => '/diandi_website/ad/index',
        'order' => 0,
        'data' => NULL,
        'type' => '',
        'level_type' => 3,
        'icon' => '',
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/ad/index',
          'item_id' => 13273,
          'route_name' => 'diandi-website-ad-index',
          'is_sys' => 0,
          'route_type' => 0,
          'description' => NULL,
          'title' => NULL,
          'pid' => 0,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => 'diandi-website-ad-index',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
      ),
      1 => 
      array (
        'name' => '幻灯片',
        'route' => '/diandi_website/slide/index',
        'order' => 1,
        'data' => NULL,
        'type' => '',
        'level_type' => 3,
        'icon' => 'fa fa-clone',
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/slide/index',
          'item_id' => 13336,
          'route_name' => 'diandi-website-slide-index',
          'is_sys' => 0,
          'route_type' => 0,
          'description' => NULL,
          'title' => NULL,
          'pid' => 0,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => 'diandi-website-slide-index',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
      ),
    ),
  ),
  1 => 
  array (
    'name' => '文章',
    'route' => '/diandi_website/article/index',
    'order' => 1,
    'data' => NULL,
    'type' => '',
    'level_type' => 1,
    'icon' => 'fa fa-commenting',
    'is_sys' => 'addons',
    'module_name' => 'diandi_website',
    'is_show' => 0,
    'ruoter' => 
    array (
      'name' => '/diandi_website/article/index',
      'item_id' => 13287,
      'route_name' => 'diandi-website-article-index',
      'is_sys' => 0,
      'route_type' => 0,
      'description' => NULL,
      'title' => NULL,
      'pid' => 0,
      'data' => NULL,
      'module_name' => 'diandi_website',
      'item' => 
      array (
        'name' => 'diandi-website-article-index',
        'is_sys' => 0,
        'permission_type' => 0,
        'description' => NULL,
        'rule_name' => 0,
        'parent_id' => 0,
        'permission_level' => 0,
        'data' => NULL,
        'module_name' => 'diandi_website',
      ),
    ),
    'level' => 3,
    'child' => 
    array (
      0 => 
      array (
        'name' => '文章分类',
        'route' => '/diandi_website/article-category/index',
        'order' => 0,
        'data' => NULL,
        'type' => '',
        'level_type' => 3,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/article-category/index',
          'item_id' => 13280,
          'route_name' => 'diandi-website-article-category-index',
          'is_sys' => 0,
          'route_type' => 0,
          'description' => NULL,
          'title' => NULL,
          'pid' => 0,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => 'diandi-website-article-category-index',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
      ),
      1 => 
      array (
        'name' => '文章',
        'route' => '/diandi_website/article/index',
        'order' => 0,
        'data' => NULL,
        'type' => '',
        'level_type' => 3,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/article/index',
          'item_id' => 13287,
          'route_name' => 'diandi-website-article-index',
          'is_sys' => 0,
          'route_type' => 0,
          'description' => NULL,
          'title' => NULL,
          'pid' => 0,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => 'diandi-website-article-index',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '添加文章',
            'route' => '/diandi_website/article/website_article_add.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => NULL,
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/article/website_article_add.vue',
              'item_id' => 14040,
              'route_name' => 'website-article-add',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => NULL,
              'title' => '添加文章',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/article/website_article_add.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '编辑文章',
            'route' => '/diandi_website/article/website_article_edit.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/article/website_article_edit.vue',
              'item_id' => 14041,
              'route_name' => 'website-article-edit',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => '',
              'title' => '编辑文章',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/article/website_article_edit.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
    ),
  ),
  2 => 
  array (
    'name' => '页面',
    'route' => '/diandi_website/page/index',
    'order' => 1,
    'data' => NULL,
    'type' => '',
    'level_type' => 1,
    'icon' => 'fa fa-calendar-check-o',
    'is_sys' => 'addons',
    'module_name' => 'diandi_website',
    'is_show' => 0,
    'ruoter' => 
    array (
      'name' => '/diandi_website/page/index',
      'item_id' => 13329,
      'route_name' => 'diandi-website-page-index',
      'is_sys' => 0,
      'route_type' => 0,
      'description' => NULL,
      'title' => NULL,
      'pid' => 0,
      'data' => NULL,
      'module_name' => 'diandi_website',
      'item' => 
      array (
        'name' => 'diandi-website-page-index',
        'is_sys' => 0,
        'permission_type' => 0,
        'description' => NULL,
        'rule_name' => 0,
        'parent_id' => 0,
        'permission_level' => 0,
        'data' => NULL,
        'module_name' => 'diandi_website',
      ),
    ),
    'level' => 3,
    'child' => 
    array (
      0 => 
      array (
        'name' => '单页面',
        'route' => '/diandi_website/page/index',
        'order' => 0,
        'data' => NULL,
        'type' => '',
        'level_type' => 3,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/page/index',
          'item_id' => 13329,
          'route_name' => 'diandi-website-page-index',
          'is_sys' => 0,
          'route_type' => 0,
          'description' => NULL,
          'title' => NULL,
          'pid' => 0,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => 'diandi-website-page-index',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
      ),
      1 => 
      array (
        'name' => '页面配置',
        'route' => '/diandi_website/pageset/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => '',
        'level_type' => 4,
        'icon' => '',
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/pageset/index.vue',
          'item_id' => 14135,
          'route_name' => 'diandi-website-pageset-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '页面配置',
          'pid' => NULL,
          'data' => '',
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/pageset/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
      ),
    ),
  ),
  3 => 
  array (
    'name' => '配置',
    'route' => '/diandi_website/nav/index',
    'order' => 1,
    'data' => NULL,
    'type' => NULL,
    'level_type' => 1,
    'icon' => 'fa fa-black-tie',
    'is_sys' => 'addons',
    'module_name' => 'diandi_website',
    'is_show' => 0,
    'ruoter' => 
    array (
      'name' => '/diandi_website/nav/index',
      'item_id' => 13473,
      'route_name' => 'diandi-website-nav-index',
      'is_sys' => 0,
      'route_type' => 0,
      'description' => NULL,
      'title' => NULL,
      'pid' => 0,
      'data' => NULL,
      'module_name' => 'diandi_website',
      'item' => 
      array (
        'name' => 'diandi-website-nav-index',
        'is_sys' => 0,
        'permission_type' => 0,
        'description' => NULL,
        'rule_name' => 0,
        'parent_id' => 0,
        'permission_level' => 0,
        'data' => NULL,
        'module_name' => 'diandi_website',
      ),
    ),
    'level' => 3,
    'child' => 
    array (
      0 => 
      array (
        'name' => '导航',
        'route' => '/diandi_website/nav/index',
        'order' => 1,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 3,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/nav/index',
          'item_id' => 13473,
          'route_name' => 'diandi-website-nav-index',
          'is_sys' => 0,
          'route_type' => 0,
          'description' => NULL,
          'title' => NULL,
          'pid' => 0,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => 'diandi-website-nav-index',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
      ),
      1 => 
      array (
        'name' => '站点信息',
        'route' => '/diandi_website/contact/index',
        'order' => 0,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 3,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/contact/index',
          'item_id' => 13301,
          'route_name' => 'diandi-website-contact-index',
          'is_sys' => 0,
          'route_type' => 0,
          'description' => NULL,
          'title' => NULL,
          'pid' => 0,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => 'diandi-website-contact-index',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
      ),
      2 => 
      array (
        'name' => '友情链接',
        'route' => '/diandi_website/link/index',
        'order' => 1,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 3,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/link/index',
          'item_id' => 13488,
          'route_name' => 'diandi-website-link-index',
          'is_sys' => 0,
          'route_type' => 0,
          'description' => NULL,
          'title' => NULL,
          'pid' => 0,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => 'diandi-website-link-index',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
      ),
    ),
  ),
  4 => 
  array (
    'name' => '首页',
    'route' => '/diandi_website/default/index.vue',
    'order' => 0,
    'data' => NULL,
    'type' => '',
    'level_type' => 1,
    'icon' => '',
    'is_sys' => 'addons',
    'module_name' => 'diandi_website',
    'is_show' => 0,
    'ruoter' => 
    array (
      'name' => '/diandi_website/default/index.vue',
      'item_id' => 13479,
      'route_name' => 'website-default-index',
      'is_sys' => 0,
      'route_type' => 1,
      'description' => '',
      'title' => '企业官网首页',
      'pid' => 0,
      'data' => '',
      'module_name' => 'diandi_website',
      'item' => 
      array (
        'name' => '/diandi_website/default/index.vue',
        'is_sys' => 0,
        'permission_type' => 0,
        'description' => NULL,
        'rule_name' => 0,
        'parent_id' => 0,
        'permission_level' => 0,
        'data' => NULL,
        'module_name' => 'diandi_website',
      ),
    ),
    'level' => 3,
    'child' => 
    array (
      0 => 
      array (
        'name' => '首页',
        'route' => '/diandi_website/default/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => '',
        'level_type' => 4,
        'icon' => '',
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/default/index.vue',
          'item_id' => 13479,
          'route_name' => 'website-default-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '企业官网首页',
          'pid' => 0,
          'data' => '',
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/default/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
      ),
    ),
  ),
  5 => 
  array (
    'name' => '产品',
    'route' => '/diandi_website/product/corefunction/index.vue',
    'order' => 5,
    'data' => NULL,
    'type' => '',
    'level_type' => 2,
    'icon' => '',
    'is_sys' => 'addons',
    'module_name' => 'diandi_website',
    'is_show' => 0,
    'ruoter' => 
    array (
      'name' => '/diandi_website/product/corefunction/index.vue',
      'item_id' => 14208,
      'route_name' => 'product-corefunction-index',
      'is_sys' => 0,
      'route_type' => 1,
      'description' => NULL,
      'title' => '核心功能',
      'pid' => NULL,
      'data' => NULL,
      'module_name' => 'diandi_website',
      'item' => 
      array (
        'name' => '/diandi_website/product/corefunction/index.vue',
        'is_sys' => 0,
        'permission_type' => 0,
        'description' => NULL,
        'rule_name' => 0,
        'parent_id' => 0,
        'permission_level' => 0,
        'data' => NULL,
        'module_name' => 'diandi_website',
      ),
    ),
    'level' => 3,
    'child' => 
    array (
      0 => 
      array (
        'name' => '核心功能',
        'route' => '/diandi_website/product/corefunction/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 4,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/corefunction/index.vue',
          'item_id' => 14208,
          'route_name' => 'product-corefunction-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '核心功能',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/corefunction/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => 'h核心功能新建',
            'route' => '/diandi_website/product/corefunction/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/corefunction/create.vue',
              'item_id' => 14209,
              'route_name' => 'product-corefunction-create',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => '',
              'title' => '核心功能新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/corefunction/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '核心功能修改',
            'route' => '/diandi_website/product/corefunction/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/corefunction/update.vue',
              'item_id' => 14210,
              'route_name' => 'product-corefunction-update',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => '',
              'title' => '核心功能修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/corefunction/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      1 => 
      array (
        'name' => '核心卖点',
        'route' => '/diandi_website/product/corecoll/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 4,
        'icon' => '',
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/corecoll/index.vue',
          'item_id' => 14211,
          'route_name' => 'product-corecoll-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '核心卖点',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/corecoll/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '核心卖点新建',
            'route' => '/diandi_website/product/corecoll/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/corecoll/create.vue',
              'item_id' => 14212,
              'route_name' => 'product-corecoll-create',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => NULL,
              'title' => '核心卖点新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/corecoll/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '核心卖点修改',
            'route' => '/diandi_website/product/corecoll/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/corecoll/update.vue',
              'item_id' => 14213,
              'route_name' => 'product-corecoll-update',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => '',
              'title' => '核心卖点修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/corecoll/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      2 => 
      array (
        'name' => '产品介绍',
        'route' => '/diandi_website/product/protop/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => '',
        'level_type' => 4,
        'icon' => '',
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/protop/index.vue',
          'item_id' => 14217,
          'route_name' => 'product-protop-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '产品介绍',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/protop/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '产品介绍新建',
            'route' => '/diandi_website/product/protop/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/protop/create.vue',
              'item_id' => 14218,
              'route_name' => 'product-protop-create',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => NULL,
              'title' => '产品介绍新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/protop/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '产品介绍修改',
            'route' => '/diandi_website/product/protop/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/protop/update.vue',
              'item_id' => 14219,
              'route_name' => 'product-protop-update',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => '',
              'title' => '产品介绍修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/protop/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      3 => 
      array (
        'name' => '产品营销',
        'route' => '/diandi_website/product/probody/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => '',
        'level_type' => 4,
        'icon' => '',
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/probody/index.vue',
          'item_id' => 14220,
          'route_name' => 'product-probody-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '产品营销',
          'pid' => 0,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/probody/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '产品营销新建',
            'route' => '/diandi_website/product/probody/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => '',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/probody/create.vue',
              'item_id' => 14221,
              'route_name' => 'product-probody-create',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => NULL,
              'title' => '产品营销新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/probody/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '产品营销修改',
            'route' => '/diandi_website/product/probody/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => '',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/probody/update.vue',
              'item_id' => 14222,
              'route_name' => 'product-probody-update',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => '',
              'title' => '产品营销修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/probody/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      4 => 
      array (
        'name' => '产品插件',
        'route' => '/diandi_website/product/plug/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 4,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/plug/index.vue',
          'item_id' => 14223,
          'route_name' => 'product-plug-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '产品插件',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/plug/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '产品插件新建',
            'route' => '/diandi_website/product/plug/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/plug/create.vue',
              'item_id' => 14224,
              'route_name' => 'product-plug-create',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => NULL,
              'title' => '产品插件新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/plug/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '产品插件修改',
            'route' => '/diandi_website/product/plug/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/plug/update.vue',
              'item_id' => 14225,
              'route_name' => 'product-plug-update',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '产品插件修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/plug/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      5 => 
      array (
        'name' => '产品版本',
        'route' => '/diandi_website/product/version/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 4,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/version/index.vue',
          'item_id' => 14226,
          'route_name' => 'product-version-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '产品版本',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/version/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '产品版本新建',
            'route' => '/diandi_website/product/version/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/version/create.vue',
              'item_id' => 14227,
              'route_name' => 'product-version-create',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => NULL,
              'title' => '产品版本新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/version/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '产品版本修改',
            'route' => '/diandi_website/product/version/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/version/update.vue',
              'item_id' => 14228,
              'route_name' => 'product-version-update',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '产品版本修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/version/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      6 => 
      array (
        'name' => '幻灯片',
        'route' => '/diandi_website/product/slide/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => '',
        'level_type' => 4,
        'icon' => '',
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 1,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/slide/index.vue',
          'item_id' => 14229,
          'route_name' => 'product-slide-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '幻灯片',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/slide/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '幻灯片新建',
            'route' => '/diandi_website/product/slide/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/slide/create.vue',
              'item_id' => 14230,
              'route_name' => 'product-slide-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => NULL,
              'title' => '幻灯片新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/slide/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '幻灯片修改',
            'route' => '/diandi_website/product/slide/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/slide/update.vue',
              'item_id' => 14231,
              'route_name' => 'product-slide-update',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '幻灯片修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/slide/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      7 => 
      array (
        'name' => '后台展示',
        'route' => '/diandi_website/product/exhibit/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => '',
        'level_type' => 4,
        'icon' => '',
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/exhibit/index.vue',
          'item_id' => 14245,
          'route_name' => 'product-exhibit-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '后台展示',
          'pid' => NULL,
          'data' => '',
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/exhibit/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '后台展示新建',
            'route' => '/diandi_website/product/exhibit/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => '',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/exhibit/create.vue',
              'item_id' => 14246,
              'route_name' => 'product-exhibit-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '后台展示新建',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/exhibit/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '后台展示修改',
            'route' => '/diandi_website/product/exhibit/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => '',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/exhibit/update.vue',
              'item_id' => 14247,
              'route_name' => 'product-exhibit-update',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '后台展示修改',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/exhibit/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      8 => 
      array (
        'name' => '产品价格',
        'route' => '/diandi_website/product/price/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 4,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/price/index.vue',
          'item_id' => 14248,
          'route_name' => 'product-price-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '产品价格',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/price/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '产品价格新建',
            'route' => '/diandi_website/product/price/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/price/create.vue',
              'item_id' => 14249,
              'route_name' => 'product-price-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '产品价格新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/price/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '产品价格修改',
            'route' => '/diandi_website/product/price/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/price/update.vue',
              'item_id' => 14250,
              'route_name' => 'product-price-update',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '产品价格修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/price/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
    ),
  ),
  6 => 
  array (
    'name' => '官网',
    'route' => '/diandi_website/product/config/index.vue',
    'order' => 4,
    'data' => NULL,
    'type' => '',
    'level_type' => 1,
    'icon' => '',
    'is_sys' => 'addons',
    'module_name' => 'diandi_website',
    'is_show' => 0,
    'ruoter' => 
    array (
      'name' => '/diandi_website/product/config/index.vue',
      'item_id' => 14205,
      'route_name' => 'product/-config-index',
      'is_sys' => 0,
      'route_type' => 1,
      'description' => NULL,
      'title' => '产品全局配置',
      'pid' => NULL,
      'data' => NULL,
      'module_name' => 'diandi_website',
      'item' => 
      array (
        'name' => '/diandi_website/product/config/index.vue',
        'is_sys' => 0,
        'permission_type' => 0,
        'description' => NULL,
        'rule_name' => 0,
        'parent_id' => 0,
        'permission_level' => 0,
        'data' => NULL,
        'module_name' => 'diandi_website',
      ),
    ),
    'level' => 3,
    'child' => 
    array (
      0 => 
      array (
        'name' => '全局配置',
        'route' => '/diandi_website/product/config/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => '',
        'level_type' => 4,
        'icon' => '',
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/config/index.vue',
          'item_id' => 14205,
          'route_name' => 'product/-config-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '产品全局配置',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/config/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
      ),
      1 => 
      array (
        'name' => '客户案例',
        'route' => '/diandi_website/product/customer/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => '',
        'level_type' => 4,
        'icon' => '',
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/customer/index.vue',
          'item_id' => 14214,
          'route_name' => 'product-customer-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '客户案例',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/customer/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '客户案例新建',
            'route' => '/diandi_website/product/customer/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/customer/create.vue',
              'item_id' => 14215,
              'route_name' => 'product-customer-create',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => NULL,
              'title' => '客户案例新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/customer/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '客户案例修改',
            'route' => '/diandi_website/product/customer/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/customer/update.vue',
              'item_id' => 14216,
              'route_name' => 'product-customer-update',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => '',
              'title' => '客户案例修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/customer/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      2 => 
      array (
        'name' => '解决方案分类',
        'route' => '/diandi_website/product/solutcate/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 4,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/solutcate/index.vue',
          'item_id' => 14252,
          'route_name' => 'product-solutcate-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '解决方案分类',
          'pid' => NULL,
          'data' => '',
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/solutcate/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '解决方案分类新建',
            'route' => '/diandi_website/product/solutcate/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/solutcate/create.vue',
              'item_id' => 14253,
              'route_name' => 'product-solutcate-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '解决方案分类新建',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/solutcate/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '解决方案分类修改',
            'route' => '/diandi_website/product/solutcate/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/solutcate/update.vue',
              'item_id' => 14254,
              'route_name' => 'product-solutcate-update',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '解决方案分类修改',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/solutcate/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      3 => 
      array (
        'name' => '解决方案',
        'route' => '/diandi_website/product/solution/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 4,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/solution/index.vue',
          'item_id' => 14255,
          'route_name' => 'product-solution-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '解决方案',
          'pid' => NULL,
          'data' => '',
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/solution/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '解决方案新建',
            'route' => '/diandi_website/product/solution/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => NULL,
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/solution/create.vue',
              'item_id' => 14256,
              'route_name' => 'product-solution-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '解决方案新建',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/solution/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '解决方案修改',
            'route' => '/diandi_website/product/solution/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => '',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/solution/update.vue',
              'item_id' => 14257,
              'route_name' => 'product-solution-update',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '解决方案修改',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/solution/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      4 => 
      array (
        'name' => '系统功能分类',
        'route' => '/diandi_website/product/sysfuncate/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 4,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/sysfuncate/index.vue',
          'item_id' => 14258,
          'route_name' => 'product-sysfuncate-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '系统功能',
          'pid' => NULL,
          'data' => '',
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/sysfuncate/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '系统功能分类新建',
            'route' => '/diandi_website/product/sysfuncate/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/sysfuncate/create.vue',
              'item_id' => 14259,
              'route_name' => 'product-sysfuncate-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '系统功能分类新建',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/sysfuncate/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '系统功能分类修改',
            'route' => '/diandi_website/product/sysfuncate/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/sysfuncate/update.vue',
              'item_id' => 14260,
              'route_name' => 'product-sysfuncate-update',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '系统功能分类修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/sysfuncate/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      5 => 
      array (
        'name' => '系统功能',
        'route' => '/diandi_website/product/systemfun/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 4,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/systemfun/index.vue',
          'item_id' => 14261,
          'route_name' => 'product-systemfun-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '系统功能',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/systemfun/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '系统功能新建',
            'route' => '/diandi_website/product/systemfun/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/systemfun/create.vue',
              'item_id' => 14262,
              'route_name' => 'product-systemfun-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '系统功能新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/systemfun/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '系统功能修改',
            'route' => '/diandi_website/product/systemfun/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/systemfun/update.vue',
              'item_id' => 14263,
              'route_name' => 'product-systemfun-update',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '系统功能修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/systemfun/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
      6 => 
      array (
        'name' => '系统价值',
        'route' => '/diandi_website/product/worth/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => NULL,
        'level_type' => 4,
        'icon' => NULL,
        'is_sys' => 'addons',
        'module_name' => 'diandi_website',
        'is_show' => 0,
        'ruoter' => 
        array (
          'name' => '/diandi_website/product/worth/index.vue',
          'item_id' => 14264,
          'route_name' => 'product-worth-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '系统价值',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_website',
          'item' => 
          array (
            'name' => '/diandi_website/product/worth/index.vue',
            'is_sys' => 0,
            'permission_type' => 0,
            'description' => NULL,
            'rule_name' => 0,
            'parent_id' => 0,
            'permission_level' => 0,
            'data' => NULL,
            'module_name' => 'diandi_website',
          ),
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '系统价值新建',
            'route' => '/diandi_website/product/worth/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/worth/create.vue',
              'item_id' => 14265,
              'route_name' => 'product-worth-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => NULL,
              'title' => '系统价值新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/worth/create.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '系统价值修改',
            'route' => '/diandi_website/product/worth/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => NULL,
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 'addons',
            'module_name' => 'diandi_website',
            'is_show' => 1,
            'ruoter' => 
            array (
              'name' => '/diandi_website/product/worth/update.vue',
              'item_id' => 14266,
              'route_name' => 'product-worth-update',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '系统价值修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_website',
              'item' => 
              array (
                'name' => '/diandi_website/product/worth/update.vue',
                'is_sys' => 0,
                'permission_type' => 0,
                'description' => NULL,
                'rule_name' => 0,
                'parent_id' => 0,
                'permission_level' => 0,
                'data' => NULL,
                'module_name' => 'diandi_website',
              ),
            ),
            'level' => 5,
          ),
        ),
      ),
    ),
  ),
);