<?php return array (
  0 => 
  array (
    'name' => '房间',
    'route' => '/diandi_tea/config/config-house.vue',
    'order' => 2,
    'data' => NULL,
    'type' => 'plugins',
    'level_type' => 1,
    'icon' => 'tea-room',
    'is_sys' => 0,
    'module_name' => 'diandi_tea',
    'is_show' => 0,
    'router' => 
    array (
      'name' => '/diandi_tea/config/meal/index.vue',
      'item_id' => 14047,
      'route_name' => 'diandi-tea-config-meal-index',
      'is_sys' => 0,
      'route_type' => 1,
      'description' => '',
      'title' => '包间套餐',
      'pid' => NULL,
      'data' => '',
      'module_name' => 'diandi_tea',
      'item' => NULL,
    ),
    'level' => 3,
    'child' => 
    array (
      0 => 
      array (
        'name' => '套餐关联',
        'route' => '/diandi_tea/config/meal/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-tea-house',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/config/meal/index.vue',
          'item_id' => 14047,
          'route_name' => 'diandi-tea-config-meal-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '包间套餐',
          'pid' => NULL,
          'data' => '',
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '新建套餐关联',
            'route' => '/diandi_tea/config/meal/create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/config/meal/create.vue',
              'item_id' => 14051,
              'route_name' => 'diandi-tea-config-meal-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '新建关联套餐',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '编辑套餐关联',
            'route' => '/diandi_tea/config/meal/update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/config/meal/update.vue',
              'item_id' => 14052,
              'route_name' => 'diandi-tea-config-meal-update',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '修改关联套餐',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
      1 => 
      array (
        'name' => '商户配置',
        'route' => '/diandi_tea/config/config-sys.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-user-profile',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/config/config-sys.vue',
          'item_id' => 14048,
          'route_name' => 'diandi-tea-config-sys',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '茶室全局配置',
          'pid' => 0,
          'data' => '',
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '商户配置新建',
            'route' => '/diandi_tea/config/config-sys-create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/config/config-sys-create.vue',
              'item_id' => 14062,
              'route_name' => 'config-config-sys-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '商户配置新建',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '商户配置修改',
            'route' => '/diandi_tea/config/config-sys-update.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/config/config-sys-update.vue',
              'item_id' => 14063,
              'route_name' => 'config-config-sys-update',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '商户配置修改',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
      2 => 
      array (
        'name' => '幻灯片',
        'route' => '/diandi_tea/config/config-slide.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-slide',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/config/config-slide.vue',
          'item_id' => 14077,
          'route_name' => 'config-config-slide',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '幻灯片',
          'pid' => NULL,
          'data' => '',
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '幻灯片新建',
            'route' => '/diandi_tea/config/config-slide-create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/config/config-slide-create.vue',
              'item_id' => 14078,
              'route_name' => 'config-config-slide-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '幻灯片新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '幻灯片修改',
            'route' => '/diandi_tea/config/config-slide-edit.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/config/config-slide-edit.vue',
              'item_id' => 14079,
              'route_name' => 'config-config-slide-edit',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '幻灯片修改',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
    ),
  ),
  1 => 
  array (
    'name' => '营销',
    'route' => '/diandi_tea/marketing',
    'order' => 4,
    'data' => NULL,
    'type' => 'plugins',
    'level_type' => 1,
    'icon' => 'tea-marketing',
    'is_sys' => 0,
    'module_name' => 'diandi_tea',
    'is_show' => 0,
    'router' => 
    array (
      'name' => '/diandi_tea/marketing',
      'item_id' => 14049,
      'route_name' => 'diandi-tea-marketing',
      'is_sys' => 0,
      'route_type' => 0,
      'description' => '',
      'title' => '茶室营销',
      'pid' => NULL,
      'data' => '',
      'module_name' => 'diandi_tea',
      'item' => NULL,
    ),
    'level' => 3,
    'child' => 
    array (
      0 => 
      array (
        'name' => '卡券',
        'route' => '/diandi_tea/marketing/coupon-marketing/coupon-marketing-index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-card-coupon',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/marketing/coupon-marketing/coupon-marketing-index.vue',
          'item_id' => 14058,
          'route_name' => 'diandi-tea-marketing-coupon-marketing-coupon-marketing-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '营销卡券',
          'pid' => NULL,
          'data' => '',
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '卡券新建',
            'route' => '/diandi_tea/marketing/coupon-marketing/coupon-marketing-create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/marketing/coupon-marketing/coupon-marketing-create.vue',
              'item_id' => NULL,
              'route_name' => 'diandi-tea-marketing-coupon-marketing-coupon-marketing-create',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => NULL,
              'title' => '营销卡券新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '卡券修改',
            'route' => '/diandi_tea/marketing/coupon-marketing/coupon-marketing-edit.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/marketing/coupon-marketing/coupon-marketing-edit.vue',
              'item_id' => 14061,
              'route_name' => 'diandi-tea-marketing-coupon-marketing-coupon-marketing-edit',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => NULL,
              'title' => '营销卡券修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
      1 => 
      array (
        'name' => '套餐',
        'route' => '/diandi_tea/marketing/set-meal/set-meal-index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-package',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/marketing/set-meal/set-meal-index.vue',
          'item_id' => 14050,
          'route_name' => 'marketing-set-meal-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '套餐管理',
          'pid' => NULL,
          'data' => '',
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '套餐新建',
            'route' => '/diandi_tea/marketing/set-meal/set-meal-create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/marketing/set-meal/set-meal-create.vue',
              'item_id' => 14057,
              'route_name' => 'diandi-tea-marketing-set-meal-set-meal-create',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => '',
              'title' => '营销套餐新建',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '套餐修改',
            'route' => '/diandi_tea/marketing/set-meal/set-meal-edit.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/marketing/set-meal/set-meal-edit.vue',
              'item_id' => 14058,
              'route_name' => 'diandi-tea-marketing-set-meal-set-meal-edit',
              'is_sys' => 0,
              'route_type' => 1,
              'description' => '',
              'title' => '营销套餐修改',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
      2 => 
      array (
        'name' => '会员卡券',
        'route' => '/diandi_tea/marketing/member-coupon/member-coupon-index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-membership-coupon',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/marketing/member-coupon/member-coupon-index.vue',
          'item_id' => 14080,
          'route_name' => 'marketing-member-coupon-member-coupon-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '会员卡券',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '会员卡券新建',
            'route' => '/diandi_tea/marketing/member-coupon/member-coupon-create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/marketing/member-coupon/member-coupon-create.vue',
              'item_id' => 14081,
              'route_name' => 'marketing-member-coupon-member-coupon-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '会员卡券新建',
              'pid' => NULL,
              'data' => '',
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '会员卡券详情',
            'route' => '/diandi_tea/marketing/member-coupon/member-coupon-edit.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/marketing/member-coupon/member-coupon-edit.vue',
              'item_id' => 14082,
              'route_name' => 'marketing-member-coupon-member-coupon-edit',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '会员卡券修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
    ),
  ),
  2 => 
  array (
    'name' => '订单',
    'route' => '/diandi_tea/order/order/order-index.vue',
    'order' => 3,
    'data' => NULL,
    'type' => 'plugins',
    'level_type' => NULL,
    'icon' => 'tea-order-goods',
    'is_sys' => 0,
    'module_name' => 'diandi_tea',
    'is_show' => 0,
    'router' => 
    array (
      'name' => '/diandi_tea/order/order/order-index.vue',
      'item_id' => 14060,
      'route_name' => 'tea-order-index',
      'is_sys' => 0,
      'route_type' => 1,
      'description' => '',
      'title' => '茶室订单',
      'pid' => NULL,
      'data' => NULL,
      'module_name' => 'diandi_tea',
      'item' => NULL,
    ),
    'level' => 3,
    'child' => 
    array (
      0 => 
      array (
        'name' => '充值活动',
        'route' => '/diandi_tea/order/rechange/rechange-index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-recharge-activity',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/order/rechange/rechange-index.vue',
          'item_id' => 14064,
          'route_name' => 'order-rechange-rechange-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '充值活动',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '充值活动新建',
            'route' => '/diandi_tea/order/rechange/rechange-create.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/order/rechange/rechange-create.vue',
              'item_id' => 14065,
              'route_name' => 'order-rechange-rechange-create',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => NULL,
              'title' => '充值活动新建',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
          1 => 
          array (
            'name' => '充值活动修改',
            'route' => '/diandi_tea/order/rechange/rechange-edit.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/order/rechange/rechange-edit.vue',
              'item_id' => 14066,
              'route_name' => 'order-rechange-rechange-edit',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '充值活动修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
      1 => 
      array (
        'name' => '卡券购买',
        'route' => '/diandi_tea/order/coupon-order/coupon-order-index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-card-purchase',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/order/coupon-order/coupon-order-index.vue',
          'item_id' => 14067,
          'route_name' => 'order-coupon-order-coupon-order-index',
          'is_sys' => 0,
          'route_type' => 2,
          'description' => '',
          'title' => '卡券购买',
          'pid' => NULL,
          'data' => '',
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '卡券购买详情',
            'route' => '/diandi_tea/order/coupon-order/coupon-order-edit.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/order/coupon-order/coupon-order-edit.vue',
              'item_id' => 14069,
              'route_name' => 'order-coupon-order-coupon-order-edit',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '卡券购买修改',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
      2 => 
      array (
        'name' => '卡券使用记录',
        'route' => '/diandi_tea/order/coupon-log/coupon-log-index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-record-usage',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/order/coupon-log/coupon-log-index.vue',
          'item_id' => 14070,
          'route_name' => 'order-coupon-log-coupon-log-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '卡券使用记录',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '卡券使用记录详情',
            'route' => '/diandi_tea/order/coupon-log/coupon-log-edit.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/order/coupon-log/coupon-log-edit.vue',
              'item_id' => 14071,
              'route_name' => 'order-coupon-log-coupon-log-edit',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => NULL,
              'title' => '卡券使用记录详情',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
      3 => 
      array (
        'name' => '订单记录',
        'route' => '/diandi_tea/order/order/order-index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-order-record',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/order/order/order-index.vue',
          'item_id' => 14060,
          'route_name' => 'tea-order-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '茶室订单',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '订单记录详情',
            'route' => '/diandi_tea/order/order/order-edit.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/order/order/order-edit.vue',
              'item_id' => 14072,
              'route_name' => 'order-order-order-edit',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '茶室订单详情',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
      4 => 
      array (
        'name' => '充值列表',
        'route' => '/diandi_tea/order/money/money-index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-recharge-list',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/order/money/money-index.vue',
          'item_id' => 14074,
          'route_name' => 'order-money-money-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '充值列表',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '充值列表详情',
            'route' => '/diandi_tea/order/money/money-edit.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/order/money/money-edit.vue',
              'item_id' => 14073,
              'route_name' => 'order-money-money-edit',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => NULL,
              'title' => '充值列表详情',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
      5 => 
      array (
        'name' => '套餐选用记录',
        'route' => '/diandi_tea/order/set-meal-list/set-meal-list-index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-recharge-list',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/order/set-meal-list/set-meal-list-index.vue',
          'item_id' => 14075,
          'route_name' => 'order-set-meal-list-set-meal-list-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '套餐选用记录',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '套餐选用记录详情',
            'route' => '/diandi_tea/order/set-meal-list/set-meal-list-edit.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/order/set-meal-list/set-meal-list-edit.vue',
              'item_id' => 14076,
              'route_name' => 'order-set-meal-list-set-meal-list-edit',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '套餐选用记录详情',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
      6 => 
      array (
        'name' => '发票',
        'route' => '/diandi_tea/order/invoice/invoice-index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => 'tea-invoice',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/order/invoice/invoice-index.vue',
          'item_id' => 14187,
          'route_name' => 'order-invoice-invoice-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '发票',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
        'child' => 
        array (
          0 => 
          array (
            'name' => '发票详情',
            'route' => '/diandi_tea/order/invoice/invoice-edit.vue',
            'order' => 0,
            'data' => NULL,
            'type' => 'plugins',
            'level_type' => 6,
            'icon' => '',
            'is_sys' => 0,
            'module_name' => 'diandi_tea',
            'is_show' => 1,
            'router' => 
            array (
              'name' => '/diandi_tea/order/invoice/invoice-edit.vue',
              'item_id' => 14188,
              'route_name' => 'order-invoice-invoice-edit',
              'is_sys' => 0,
              'route_type' => 2,
              'description' => '',
              'title' => '发票详情',
              'pid' => NULL,
              'data' => NULL,
              'module_name' => 'diandi_tea',
              'item' => NULL,
            ),
            'level' => 5,
          ),
        ),
      ),
    ),
  ),
  3 => 
  array (
    'name' => '首页',
    'route' => '/diandi_tea/default/index.vue',
    'order' => 0,
    'data' => NULL,
    'type' => 'plugins',
    'level_type' => 1,
    'icon' => 'tea-home-page',
    'is_sys' => 0,
    'module_name' => 'diandi_tea',
    'is_show' => 0,
    'router' => 
    array (
      'name' => '/diandi_tea/default/index.vue',
      'item_id' => 14046,
      'route_name' => 'diandi-tea-index',
      'is_sys' => 0,
      'route_type' => 1,
      'description' => '',
      'title' => '首页',
      'pid' => NULL,
      'data' => '',
      'module_name' => 'diandi_tea',
      'item' => NULL,
    ),
    'level' => 3,
    'child' => 
    array (
      0 => 
      array (
        'name' => '首页',
        'route' => '/diandi_tea/default/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => '',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/default/index.vue',
          'item_id' => 14046,
          'route_name' => 'diandi-tea-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => '',
          'title' => '首页',
          'pid' => NULL,
          'data' => '',
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
      ),
    ),
  ),
  4 => 
  array (
    'name' => '统计',
    'route' => '/diandi_tea/statistics/index.vue',
    'order' => 5,
    'data' => NULL,
    'type' => 'plugins',
    'level_type' => 1,
    'icon' => 'tea-statistics',
    'is_sys' => 0,
    'module_name' => 'diandi_tea',
    'is_show' => 0,
    'router' => 
    array (
      'name' => '/diandi_tea/statistics/index.vue',
      'item_id' => 14189,
      'route_name' => 'statistics-index',
      'is_sys' => 0,
      'route_type' => 1,
      'description' => NULL,
      'title' => '统计',
      'pid' => NULL,
      'data' => NULL,
      'module_name' => 'diandi_tea',
      'item' => NULL,
    ),
    'level' => 3,
    'child' => 
    array (
      0 => 
      array (
        'name' => '统计',
        'route' => '/diandi_tea/statistics/index.vue',
        'order' => 0,
        'data' => NULL,
        'type' => 'plugins',
        'level_type' => 4,
        'icon' => '',
        'is_sys' => 0,
        'module_name' => 'diandi_tea',
        'is_show' => 0,
        'router' => 
        array (
          'name' => '/diandi_tea/statistics/index.vue',
          'item_id' => 14189,
          'route_name' => 'statistics-index',
          'is_sys' => 0,
          'route_type' => 1,
          'description' => NULL,
          'title' => '统计',
          'pid' => NULL,
          'data' => NULL,
          'module_name' => 'diandi_tea',
          'item' => NULL,
        ),
        'level' => 4,
      ),
    ),
  ),
);