<?php

use yii\db\Migration;

class m220801_020131_diandi_website_link extends Migration
{
    public function up()
    {
        /* 取消外键约束 */
        $this->execute('SET foreign_key_checks = 0');
        
        /* 创建表 */
        $this->createTable('{{%diandi_website_link}}', [
            'id' => "int(11) NOT NULL AUTO_INCREMENT",
            'name' => "varchar(255) NULL COMMENT '公司名称'",
            'intro' => "text NULL COMMENT '简介'",
            'logo' => "varchar(255) NULL COMMENT '公司logo'",
            'wechat_code' => "varchar(255) NULL COMMENT '公众号二维码'",
            'image' => "varchar(255) NULL COMMENT '显示图片'",
            'link' => "varchar(255) NULL COMMENT '链接地址'",
            'store_id' => "int(11) NULL",
            'bloc_id' => "int(11) NULL",
            'createtime' => "varchar(30) NULL",
            'updatetime' => "varchar(30) NULL",
            'PRIMARY KEY (`id`)'
        ], "ENGINE=MyISAM  DEFAULT CHARSET=utf8 COMMENT='幻灯片'");
        
        /* 索引设置 */
        
        
        /* 表数据 */
        $this->insert('{{%diandi_website_link}}',['id'=>'1','name'=>'oracle','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/c33de6b9-0321-3468-8a8c-dc854ee33fc4.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'3','name'=>'vmwarepng','intro'=>'<p>介绍</p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/1e8243c7-5acf-31e0-b0ee-78df002a4a27.jpg','wechat_code'=>'','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'4','name'=>'阿里云','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/f2a0e89a-d9e5-3483-bb89-aee965fb960b.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'5','name'=>'爱数','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/0cc41c47-f3be-34f6-be21-53dae76973fe.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'6','name'=>'迪普','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/9f974fec-c9e4-3ac2-88db-84b8fbae05bf.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'7','name'=>'烽火','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/9eaccadc-9e80-30d1-a733-48517d40ff1a.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'8','name'=>'海康威视','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/17c49972-80e9-3664-a03b-53587c24f21e.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'9','name'=>'华为','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/df5a99a9-a7f6-3080-8785-c36c0a7661a4.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'10','name'=>'浪潮','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/50636cf8-192c-3f3e-a746-9a9aa1f03657.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'11','name'=>'绿盟','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/df924ed5-70ce-38c3-97ff-3a4db09ce41e.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'12','name'=>'青云','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/d849f751-a27c-3e23-8f99-2cd0f4adc506.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'13','name'=>'锐捷','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/5c6c0f6a-f787-33da-bf36-c633baa55c5e.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'14','name'=>'山石网科','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/8989447d-111c-3a87-a928-a673ef2c8541.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'15','name'=>'深信服','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/e206b127-c890-388b-922f-7490ae1abbeb.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        $this->insert('{{%diandi_website_link}}',['id'=>'16','name'=>'施耐德','intro'=>'<p>	<span style=\"color: rgb(0, 0, 0);\">陕西和生科技有限公司是陕西IT系统集成行业的优秀公司之一，</span><strong style=\"color: rgb(0, 0, 0);\">公司拥有中国电子工业标准化技术协会颁发的信息技术服务运行维护贰级证书、信息系统集成及服务贰级资质、公安部安全技术防范壹级资质、电子与智能化工程专业承包贰级证书；通过了ISO9001质量管理体系认证、27001信息安全管理体系认证；获得了陕西省住房和城乡建设厅颁发的安全生产许可证证书、同时获得了由陕西省国家保密局颁发的涉密信息系统集成乙级资质证书。</strong><span style=\"color: rgb(0, 0, 0);\">公司的业务领域涵盖：弱电工程、网络系统集成、网络安全及管理、高性能服务器集群系统、海量数据存储、企业数据（安全）管理、软件定制开发、IT信息技术服务及运维等。</span></p>','logo'=>'https://dev.hopesfire.com/attachment/202109/30/45d4c777-8392-33fd-afac-79a331214967.jpg','wechat_code'=>'https://dev.hopesfire.com/attachment/202109/23/0fda84d8-108f-379b-a5b9-ad53e5d5382c.png','image'=>'','link'=>'www','store_id'=>'75','bloc_id'=>'27','createtime'=>'','updatetime'=>'']);
        
        /* 设置外键约束 */
        $this->execute('SET foreign_key_checks = 1;');
    }

    public function down()
    {
        $this->execute('SET foreign_key_checks = 0');
        /* 删除表 */
        $this->dropTable('{{%diandi_website_link}}');
        $this->execute('SET foreign_key_checks = 1;');
    }
}

