<?php

use yii\db\Migration;

class m231118_000438_member extends Migration
{
    public function up()
    {
        /* 取消外键约束 */
        $this->execute('SET foreign_key_checks = 0');
        
        /* 创建表 */
        $this->createTable('{{%member}}', [
            'member_id' => "int(11) unsigned NOT NULL AUTO_INCREMENT",
            'group_id' => "int(11) NOT NULL",
            'level' => "int(11) NULL",
            'openid' => "varchar(255) NOT NULL DEFAULT ''",
            'store_id' => "int(11) NULL",
            'bloc_id' => "int(11) NOT NULL",
            'username' => "varchar(30) NULL COMMENT '会员名称'",
            'mobile' => "varchar(11) NULL COMMENT '手机号'",
            'address' => "varchar(255) NULL COMMENT '用户地址'",
            'nickName' => "varchar(255) NOT NULL DEFAULT '' COMMENT '微信昵称'",
            'avatarUrl' => "varchar(255) NOT NULL DEFAULT '' COMMENT '会员头像'",
            'gender' => "tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '0男1女'",
            'country' => "varchar(100) NOT NULL DEFAULT '' COMMENT '国家'",
            'province' => "varchar(100) NOT NULL DEFAULT '' COMMENT '省份'",
            'status' => "int(11) NULL DEFAULT '0' COMMENT '会员状态'",
            'city' => "varchar(100) NOT NULL DEFAULT '' COMMENT '城市'",
            'address_id' => "int(11) unsigned NOT NULL DEFAULT '0' COMMENT '收货地址id'",
            'invitation_code' => "varchar(100) NOT NULL DEFAULT '0'",
            'verification_token' => "varchar(255) NULL COMMENT '验证token'",
            'create_time' => "bigint(11) unsigned NOT NULL DEFAULT '0'",
            'update_time' => "bigint(11) unsigned NOT NULL DEFAULT '0'",
            'auth_key' => "varchar(32) NOT NULL",
            'password_hash' => "varchar(255) NOT NULL",
            'password_reset_token' => "varchar(255) NULL",
            'realname' => "varchar(10) NULL COMMENT '真实姓名'",
            'avatar' => "varchar(255) NULL COMMENT '头像'",
            'qq' => "varchar(10) NULL COMMENT 'QQ号'",
            'vip' => "varchar(10) NULL COMMENT 'VIP级别'",
            'birthyear' => "varchar(10) NULL COMMENT '出生生日'",
            'constellation' => "varchar(10) NULL COMMENT '星座'",
            'zodiac' => "varchar(10) NULL COMMENT '生肖'",
            'telephone' => "varchar(10) NULL COMMENT '固定电话'",
            'idcard' => "varchar(20) NULL COMMENT '证件号码'",
            'studentid' => "varchar(10) NULL COMMENT '学号'",
            'grade' => "varchar(10) NULL COMMENT '班级'",
            'zipcode' => "varchar(10) NULL COMMENT '邮编'",
            'nationality' => "varchar(10) NULL COMMENT '国籍'",
            'resideprovince' => "varchar(10) NULL COMMENT '居住地址'",
            'graduateschool' => "varchar(10) NULL COMMENT '毕业学校'",
            'company' => "varchar(10) NULL COMMENT '公司'",
            'education' => "varchar(10) NULL COMMENT '学历'",
            'occupation' => "varchar(10) NULL COMMENT '职业'",
            'position' => "varchar(10) NULL COMMENT '职位'",
            'revenue' => "varchar(10) NULL COMMENT '年收入'",
            'affectivestatus' => "varchar(10) NULL COMMENT '情感状态'",
            'lookingfor' => "varchar(10) NULL COMMENT ' 交友目的'",
            'bloodtype' => "varchar(10) NULL COMMENT '血型'",
            'height' => "varchar(10) NULL COMMENT '身高'",
            'weight' => "varchar(10) NULL COMMENT '体重'",
            'alipay' => "varchar(10) NULL COMMENT '支付宝帐号'",
            'msn' => "varchar(10) NULL COMMENT 'MSN'",
            'email' => "varchar(10) NULL COMMENT '电子邮箱'",
            'taobao' => "varchar(10) NULL COMMENT '阿里旺旺'",
            'site' => "varchar(10) NULL COMMENT '主页'",
            'bio' => "varchar(10) NULL COMMENT '自我介绍'",
            'interest' => "varchar(10) NULL COMMENT '兴趣爱好'",
            'organization_id' => "int(11) NULL COMMENT '组织机构ID'",
            'PRIMARY KEY (`member_id`)'
        ], "ENGINE=InnoDB  DEFAULT CHARSET=utf8");
        
        /* 索引设置 */
        $this->createIndex('openid','{{%member}}','openid',0);
        
        
        /* 表数据 */
        $this->insert('{{%member}}',['member_id'=>'1','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5PTTl4Y-cYL5PbB6m-6GIR8','store_id'=>'153','bloc_id'=>'91','username'=>'游客1','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar10.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'V2NYw','verification_token'=>'5rT7oVoE1SIot0lfWorpRkfeg_kb_TOA_1698743388','create_time'=>'1698742154','update_time'=>'1698743388','auth_key'=>'FJC_z6w_lHXDYCJap8JMg1yqKC4pV6Tv','password_hash'=>'$2y$13$l8zWxbfxHbHB..3WWMOh3ehHHSqQsxChhPHRac4p2RqY.Ux.eQUxm','password_reset_token'=>'lPZSLzHltdwWb4wm5GpQBMj8Q1APf4CQ_1698743388','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'2','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5FtCsQG0xoAT4Dq6X3WabH4','store_id'=>'153','bloc_id'=>'91','username'=>'游客2','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar3.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'NQnzQ','verification_token'=>'M3YUmoBwHGAXzW7LhYo7v4uBc0_s0-_j_1698742590','create_time'=>'1698742590','update_time'=>'1698742590','auth_key'=>'kIOih4_LgzoByQzesWXkZHpAhKZYOq1I','password_hash'=>'$2y$13$O8glWSN7AalCVToRh33.EuST4rhl85WYUK4Z4gmRh6ucmAQr2AP0S','password_reset_token'=>'0Nvgvz9LTQffox-NYX0aJglSNOSIxXFp_1698742590','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'3','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5M_cVCgtCI0ivBW4V0Yzrww','store_id'=>'153','bloc_id'=>'91','username'=>'游客3','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar1.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'KwGvx','verification_token'=>'juQ0imm4iCAX7t6k5Ew2TDKCalT_dLby_1698742615','create_time'=>'1698742614','update_time'=>'1698742614','auth_key'=>'ntLsqkUYNU7ni_rIk-doYvW8g5LdmFQ2','password_hash'=>'$2y$13$S5V2HglZqCMONoypGKVXjOcsc1vcrSl9BxOeGKdgDzUXc6hJAmHuO','password_reset_token'=>'QfvAcjXg8yInRPlRSMibLi5_NZlo5xFE_1698742615','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'4','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5B7UivJqMOadIGdPmsioiag','store_id'=>'153','bloc_id'=>'91','username'=>'游客4','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar8.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'p2Wk2','verification_token'=>'FBiD9LFJS9mp2ygbxVswQkHEU8BF8HUg_1698754549','create_time'=>'1698754548','update_time'=>'1698754548','auth_key'=>'OYDq5eAqhCTEWhKWaCTqaGd9DNe4Dmvr','password_hash'=>'$2y$13$lT7JFJbXcANEUMHvzlKwYuIiQ23cI2f.MnioZE9qzupyl2rVYcmFi','password_reset_token'=>'Gtq3IiLtauGQHitUfWc_njmbpMMHs7Np_1698754549','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'5','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5Ao95jrze4MEnNlftWhlpk4','store_id'=>'153','bloc_id'=>'91','username'=>'游客5','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar6.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'J2B1w','verification_token'=>'qXo61vMmteL79w7dTb4qsFf1pQ-TJdCS_1698754571','create_time'=>'1698754571','update_time'=>'1698754571','auth_key'=>'EGus_SrQIN-8yGWvQB9UOkvhWz_5H4cI','password_hash'=>'$2y$13$9pPDfmTm.c2m7hTs9cxYgegmDclzNpkft7jm.y3Fn/yqOZ5MaQIcO','password_reset_token'=>'GchlriK2joKRG3g78IczXLXd_-SQ6tbT_1698754571','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'6','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5NkNy2jyh_oXdg38yn7FbiQ','store_id'=>'153','bloc_id'=>'91','username'=>'游客6','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar7.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'n25dw','verification_token'=>'fsWKnAhDDjhJhTPvyJq3gW2GRj8f8TZh_1698754586','create_time'=>'1698754586','update_time'=>'1698754586','auth_key'=>'oC7A8FlIsv1y5G0CLV6QIEoGTtIVhZHS','password_hash'=>'$2y$13$Cx8GUIzhWAOeJh1hX1Ohs.CTxH8dAki3CpqiucWrjojq9ij7un16m','password_reset_token'=>'4SChexu7pByHZfC-_fIuAVwDOEcvDy5a_1698754586','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'7','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5NzLCimGPl1NknnXp83Q1Vs','store_id'=>'153','bloc_id'=>'91','username'=>'游客7','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar10.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'DQm42','verification_token'=>'Db9s_3r0L_lwXZGR5MFf3g_lZjaISGpD_1698754841','create_time'=>'1698754841','update_time'=>'1698754841','auth_key'=>'kRoUx_VZZ9vhXYP7rO2uEFj7Jyh4lY-Y','password_hash'=>'$2y$13$Mo0zXY112O09Sx2bMWMQ7.IHVOBYaWDGTszdzpQj1WbSSLzQoidja','password_reset_token'=>'BTmYbC4vEeTpbZv5YDYlXiAnQIeO0WDj_1698754841','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'8','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5NJ6kBmAYDekdLSEy4RIgEg','store_id'=>'153','bloc_id'=>'91','username'=>'游客8','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar1.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'YwbNw','verification_token'=>'pQdqqnau9jn15hYlldUtC27S52D0gdsz_1698754905','create_time'=>'1698754904','update_time'=>'1698754904','auth_key'=>'MLYKPhKVq9xx9BL02sFOfKouWnQu9Blt','password_hash'=>'$2y$13$KsD6ncWF4BSYBzPB8Qc72ujF0WFMrrzgKDzBRIf.vESZfYYSF22.q','password_reset_token'=>'-Bt6SF5w95LAFUxGFs0EGoXqHtem6Jxj_1698754905','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'9','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5L6xZUeNp7yybedxX6Z4hnw','store_id'=>'153','bloc_id'=>'91','username'=>'游客9','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar2.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'r2v4x','verification_token'=>'n_0S89JiELBUJydJQnISUfaCkhotgHkh_1698754961','create_time'=>'1698754960','update_time'=>'1698754960','auth_key'=>'zPdgfGTzDdjcvKxw2gu_znEJ2NbxeACo','password_hash'=>'$2y$13$vteSFkBrPramUFZt06T.NuKN24GcWC5tHCXIIIXoGTnAk/qfHQB9.','password_reset_token'=>'p3mIJtbV2CCjLqk9bQiepLjmRauvGIPt_1698754961','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'10','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5FdYH-mb8kP-wxLjxi1nxss','store_id'=>'153','bloc_id'=>'91','username'=>'游客10','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar3.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'n2MXw','verification_token'=>'JBccOOsOuV9xd3AYpq50zCkItJtOk8gv_1698755092','create_time'=>'1698755092','update_time'=>'1698755092','auth_key'=>'AKipeeECnPOgTBQwVyGIW6Jp-nFD2qw5','password_hash'=>'$2y$13$5KwTC7yD2alHnyiXMslT8.svY2giDQ6JjEcbMrer0.vVmUTuYngIy','password_reset_token'=>'wsA4-uG2fRR4F6-oQyUFBBq1cDHtSDLI_1698755092','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'11','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5ClSOW1JyK5w3BQD7abkrTE','store_id'=>'153','bloc_id'=>'91','username'=>'游客11','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar3.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'yxVD2','verification_token'=>'57Ff__Ix18xiycxHxwu9Ejb_GFsbOK7o_1698755163','create_time'=>'1698755163','update_time'=>'1698755163','auth_key'=>'EqLwG7gB4HWy7VmgXUXE52cDaR_4MgEe','password_hash'=>'$2y$13$2OUX9QnNbShzpSY15RcnOO7nyaazVXgl/ZCm8hEPkZyUSVOTLi.WC','password_reset_token'=>'_aOmi0Dxf16fUPQbm4THPFbgbE2lW2lu_1698755163','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'12','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5EZTwPGgrUEdLJH_maCMqN4','store_id'=>'153','bloc_id'=>'91','username'=>'游客12','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar3.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'pQlk2','verification_token'=>'dXLQo2xKyevvxFWrCpUm1_5gKLppGVEL_1698755206','create_time'=>'1698755205','update_time'=>'1698755205','auth_key'=>'6OrKLikGNZT2CG0xoYckKxcpdDQ9-1P8','password_hash'=>'$2y$13$gSMFWrs0I4xvzKoEAUp41ucquh5MS56G4wWihLUR6OKbezp9UdOOW','password_reset_token'=>'jDHE_KFUj4x8F4xu4EcfPDsCxFwG-hKn_1698755206','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'13','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5Jm8yFv4qqRynsvP9fW2tn4','store_id'=>'153','bloc_id'=>'91','username'=>'游客13','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar7.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'n2zyw','verification_token'=>'2mz_dYLBIUIPkhyPBJleXXgTZLiEIazl_1698755950','create_time'=>'1698755950','update_time'=>'1698755950','auth_key'=>'S-RCfXH45uftgmA2CGFKfwkWWS-qAC-Z','password_hash'=>'$2y$13$T8ETJwwFQjZ/hgjkP7cqoumpFvQ/tdyU4fGv0i7MAC3uuUl83GbjS','password_reset_token'=>'FrtyUl6IGzjioxvA1TdIx66aCRcvI6aM_1698755950','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'14','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5Jw1HSytTXxB6IE0f_ky2uw','store_id'=>'153','bloc_id'=>'91','username'=>'游客14','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar9.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'62qNQ','verification_token'=>'28PQra5ePYmV9fXyLiEhLq8Mlc6334zN_1698756390','create_time'=>'1698756389','update_time'=>'1698756389','auth_key'=>'4uwrmUCSEbluTfxztn-G-rYfcUX9Tqa8','password_hash'=>'$2y$13$zRdEp.pBjgPn8LtXJsQkOuOo63MhEPcj6gjmk5UqDYZjzMWAVM.km','password_reset_token'=>'uF9DFTRtAlQyq-ccSznw3MK7Q8LGaZYf_1698756390','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'15','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5H7ewTNUbGRLGgLejZtyJl0','store_id'=>'153','bloc_id'=>'91','username'=>'游客15','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar1.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'e2dX2','verification_token'=>'RPqzHcIfCzPmCQ21Z4pOB8qUqVmoqOo1_1698757137','create_time'=>'1698757136','update_time'=>'1698757136','auth_key'=>'aEgrtoYSofnQ0sbtZVKxIAaA5T3Xgc3F','password_hash'=>'$2y$13$8Zs3IAgaXYVJB6K9Z1OT9eH.3NAgndQgkGbQDGmhbq3qY4FeeTJxS','password_reset_token'=>'SXwFq6OXfMzPVR7gHWsp39eZd1-DMIxG_1698757137','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'16','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5LdyRcLbWNwmUV3WVokLxkI','store_id'=>'153','bloc_id'=>'91','username'=>'游客16','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar5.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'0xYg2','verification_token'=>'QGu-7Ti3jqvnP9l7x2UR_yu9t44pPb_B_1698757412','create_time'=>'1698757411','update_time'=>'1698757411','auth_key'=>'XufrpcPYut-ipdZ_VDB0zEnf_MkM420a','password_hash'=>'$2y$13$wPkyqISHFE1RmQxDCgBVVuQYHC8ZrAG6URSgDouvqfdxXukWgTGm2','password_reset_token'=>'H-iOU6AIHFDoeWzlj5FnGpBUoCPLKtxP_1698757412','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'17','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5C7Dskw3DNlpOQUwaJrDiGc','store_id'=>'153','bloc_id'=>'91','username'=>'游客17','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar7.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'Zx8Lx','verification_token'=>'7on3H35F603UAjq4F11oLN4zqqkBzlTi_1698795030','create_time'=>'1698795030','update_time'=>'1698795030','auth_key'=>'Tq0DC6LlPZpgMNmnfePZRzCFO58ZB_O8','password_hash'=>'$2y$13$z9an1iqpRgHs1XUMaSk6bOqYKmmlvPyHxCROfz91NceBam4JVT0Gi','password_reset_token'=>'jywaq-UMMG4AU11Yz2LTE7f7LS-gzozX_1698795030','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'18','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5G3Xc_EAq6474xEd7S4p--Q','store_id'=>'153','bloc_id'=>'91','username'=>'游客18','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar7.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'zxgY2','verification_token'=>'gCIeIUXoJ-kjuRgopGvWtistj6ifspx9_1698806771','create_time'=>'1698806770','update_time'=>'1698806770','auth_key'=>'YFihQooDDNvfM-WlPxLG5KkRG3V-6wqy','password_hash'=>'$2y$13$9LH3zdUwzjSzYfUai6wFrOluMl/YQRrZFheA7YEHk1gRhAPgmfF66','password_reset_token'=>'qX0SJouYdxF3gn2hUzTbtMv9_aAK-tQ1_1698806771','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'19','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5NVWrVwQZq9s4DrjEy9vSWk','store_id'=>'153','bloc_id'=>'91','username'=>'游客19','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar2.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'ZxJNx','verification_token'=>'oEOhh30F50fZ8zoT7gxzX5msEcMFEoBg_1698980443','create_time'=>'1698980442','update_time'=>'1698980442','auth_key'=>'jetTE2NJCKwGY_KK6xCBGDVI_QlADXck','password_hash'=>'$2y$13$G8nURxDigKWUWCLQy4KYk.R01wLKFQeYFLWxtgj.5zoQebaGFWzMC','password_reset_token'=>'zdieEP1xVzNO5TbB3n7ribLH6S9qoIGz_1698980443','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'20','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5G4nvZLg15cnbxpBfcVoW3k','store_id'=>'153','bloc_id'=>'91','username'=>'游客20','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar3.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'oxa8Q','verification_token'=>'EMWzvUvAP-1c_KUPZW9Kaj65_q4dQYxp_1699145244','create_time'=>'1699145243','update_time'=>'1699145243','auth_key'=>'7ZEn0KbR2lnQB4jYzn4zeK481wFFa4nP','password_hash'=>'$2y$13$AtZ6aWhKCkiBt0lLp/v.TeePlejF8HnI2NnvjRwbwsl6Kiy9HxxRa','password_reset_token'=>'AteF2YxMOLLKw9Wo7NGNvb3OWuQVs42N_1699145244','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'21','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5CsZgfMU0I4FmNywlbBizGk','store_id'=>'153','bloc_id'=>'91','username'=>'游客21','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar6.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'o2RgQ','verification_token'=>'lf635Qs0qVP1rMF3MM0F86INKwzt2l5A_1699147322','create_time'=>'1699147321','update_time'=>'1699147321','auth_key'=>'6DgE7BItV8drhb1QBPwCz603auOg5GJd','password_hash'=>'$2y$13$8NdL5Z47bBFoZQ6CcFBB2ef2kD5qq8GF7YFteOUzwsj1rOA7ZlZ6C','password_reset_token'=>'5TvJW9jGy0Ua1250_4aXbSBcd00EtFxh_1699147322','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'22','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5NmldjlmvCLcuxW2azHq3T0','store_id'=>'153','bloc_id'=>'91','username'=>'游客22','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar9.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'dwDjQ','verification_token'=>'jAXdvVPkgo3qytDu522dyHVtAeZUU0O4_1699152104','create_time'=>'1699152104','update_time'=>'1699152104','auth_key'=>'N4ZUvWDk-cP2KAoJC3Ihz-3r7i3vaZdc','password_hash'=>'$2y$13$UtJod6uIYrvUyc74YtkLquUtYHwVniAytCJ5fe8FpVv5F5nPF34Bi','password_reset_token'=>'lpKD_Lidj2ZtBjEUWxEEOkO1TSLrdMF1_1699152104','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'23','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5Dd4kAktfiwYbAFdllZJP6Y','store_id'=>'153','bloc_id'=>'91','username'=>'游客23','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar6.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'LQ1ow','verification_token'=>'OmNoZ1NiTr8c79wQhvMZvSV3m1m0U7SJ_1699173783','create_time'=>'1699173783','update_time'=>'1699173783','auth_key'=>'XHo7c-SmO1VDGHMfe0Y5BTrdvZTyGe70','password_hash'=>'$2y$13$TA63.MzuZt06RqsZ8jUSyOPlSQwisC/JZ0sMQZvMHKnDRV2exwjty','password_reset_token'=>'YAtM7MsMvAyee79mKTjveChb52fpCbhe_1699173783','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'24','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5BdNn4MLljX0EzJpIjf_mFQ','store_id'=>'153','bloc_id'=>'91','username'=>'游客24','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar8.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'V2k8Q','verification_token'=>'x229rgtT-npsidBhV0mWx4O_0-4B6ikQ_1699195552','create_time'=>'1699195551','update_time'=>'1699195551','auth_key'=>'oaoLDQo7cUGCU12rTZT7JOjN0h2foWIZ','password_hash'=>'$2y$13$5V.zNU4aJdq/9nKsOi75/OLs.ktZIemCaSRrkC2Sh5cTz0HThj6Hi','password_reset_token'=>'JHUE6YCDIECBAX_EAjOX5W91AMa9gvcL_1699195552','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'25','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5CXoqOcjv3hOxVP6Wxi8u8c','store_id'=>'153','bloc_id'=>'91','username'=>'游客25','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar2.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'jwy9w','verification_token'=>'3dQ6hclAYRcXhzKoVlKZwCQ8gh-zAqZ5_1699230060','create_time'=>'1699230059','update_time'=>'1699230059','auth_key'=>'qEUqk9lkpBls4DWutibm3qFyOtsGsMOV','password_hash'=>'$2y$13$g9mmQ20Y7E5If6y7yGcSc.kx6wibqcIttLuYDQ9ogjaHu5NxnAGZm','password_reset_token'=>'8aE8KXkDG5RJpVxsJcoa22zaYnbLOgP__1699230060','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'26','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5AqBW0XUIP-3iChLMZEcAn8','store_id'=>'153','bloc_id'=>'91','username'=>'游客26','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar6.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'dxozQ','verification_token'=>'_nzy4K6HVS79tH7s88CdnhzDQ5zcP1g5_1699230124','create_time'=>'1699230123','update_time'=>'1699230123','auth_key'=>'KsaRRBbfboMMCIrIzlJsheESlluvBDeU','password_hash'=>'$2y$13$HLaY/.fVm8acj9OIY8yrquA1h4EwV.loZWlZT7LIC7L3q23b41pSu','password_reset_token'=>'n4F9Uaz6FxNujRIfEko36D7Tkn4DmHEd_1699230124','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'27','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5HAFML4wTZcJqrcxqr9aFwg','store_id'=>'153','bloc_id'=>'91','username'=>'游客27','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar8.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'q2P02','verification_token'=>'fm_9sxyKIKeAy7tJLPMKpIcI_VvrVZpZ_1699231277','create_time'=>'1699231277','update_time'=>'1699231277','auth_key'=>'MM1bgWmw5hVWiiuqNiHS6dDERIbgQl-8','password_hash'=>'$2y$13$33rOtDX4rZG/Ur/KzxgPsO4WOPGtoAMwIK672R2GfUYTJxfCxzm3K','password_reset_token'=>'xKC3Kz4XEDcbz06zYch3Nvtm2vvYj2on_1699231277','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'28','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5KF9RcfTNGu2LD-cipYrho8','store_id'=>'153','bloc_id'=>'91','username'=>'游客28','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar2.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'LxAg2','verification_token'=>'cIjDvCpxd3jmGO2U-CeSEwNQ85v6nS3d_1699231369','create_time'=>'1699231369','update_time'=>'1699231369','auth_key'=>'YRXYGBZeeQE6leHxibuhIlABko-HrPQO','password_hash'=>'$2y$13$bldCmDlBQmdcuaNq4Qn2y.rBScnGrujEAWABMmQI2g58TLke.ncYu','password_reset_token'=>'3rh46aXL4st2LQx65gE2ED3CUHn9Wiac_1699231369','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'29','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5IzgPIWN6JSeKVfz45_hEMI','store_id'=>'153','bloc_id'=>'91','username'=>'游客29','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar5.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'AwE1w','verification_token'=>'M5IMp7sUx2JH7Zq4AKGDXN1ZcND6l7R9_1699233746','create_time'=>'1699233745','update_time'=>'1699233745','auth_key'=>'MjJMP0hADgP0rBAtqqs50XvYWlZqbMcx','password_hash'=>'$2y$13$74m0bs8zmjRzE9hazEDD9.mvM4eukbQWbnUy.VWgHq.z0cXs1Q3WK','password_reset_token'=>'VS5DOu0h-i5LS1MNPYovgpsRTMeQRCuD_1699233746','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'30','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5EvKyNqT2jsKS1BI2WrZr28','store_id'=>'153','bloc_id'=>'91','username'=>'游客30','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar1.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'V29gx','verification_token'=>'ic4YZC1RGesJoRJRsyGf3eM2ODlFHN9f_1699253167','create_time'=>'1699253167','update_time'=>'1699253167','auth_key'=>'rDsiql2Ctc7iX935nJcM53SnSbpEDtgv','password_hash'=>'$2y$13$jLlDiW3dvA59u0yMvyv7FuCc/qvFbJ392hUx9CgqZWMg8DPT1gbhK','password_reset_token'=>'tACDYES1HfVOPBoib_VIM7V7VIdXKgct_1699253167','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'31','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5EvKyNqT2jsKS1BI2WrZr28','store_id'=>'153','bloc_id'=>'91','username'=>'游客30','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar3.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'7x6aQ','verification_token'=>'mO3RlTY4uMO6mfTjz0fx5YhMd_LxVF-v_1699253167','create_time'=>'1699253167','update_time'=>'1699253167','auth_key'=>'e9_lhf_85JVnU_mhS5dI76rPeCm6NyOT','password_hash'=>'$2y$13$0JRJdJ6qowMEsfmWHDqtq.pT5XlJUVhCfo5DIT8EeMsmfmizdO.wa','password_reset_token'=>'myLnrll_dpCWqEZMjDtE5uE1LLlTSGXl_1699253167','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'32','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5Hw_SOS9trmuoC3YpRcCZwg','store_id'=>'153','bloc_id'=>'91','username'=>'游客32','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar1.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'VwZ9x','verification_token'=>'pmth5gave171lQTlink3k-u4dydFUcFg_1699306336','create_time'=>'1699306335','update_time'=>'1699306335','auth_key'=>'_mwZHAK3aGKlLlcbgjPRvh89D4d-ORCG','password_hash'=>'$2y$13$BZpCBds9vA3smt5fkvXHr..wa8wZLdVRNcXy0Ue76iTAYMY2oB8XC','password_reset_token'=>'1FtxfXON2IprPr5JSIcDGcMe00YrOwZS_1699306336','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'33','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5B3v-kUqSseT3iRYKZWZo0o','store_id'=>'153','bloc_id'=>'91','username'=>'游客33','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar4.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'bx4Lx','verification_token'=>'koLK7VqN4Dx4bPB5tjRu0b3XI0YuAnEH_1699321047','create_time'=>'1699321046','update_time'=>'1699321046','auth_key'=>'TfGV6-eLH3sol8hRZdqpeyerc9Vn7jly','password_hash'=>'$2y$13$KutDT/i8KwasSWzi6q.0GeenNO/WKj8ZoKaGFXmrmt4/p/My7hel2','password_reset_token'=>'zLaYJmHeHZRiZVmyB5EDFNRKVzFwJqOG_1699321047','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'34','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5EpqzP_C-4tjLfTSKMALbdw','store_id'=>'153','bloc_id'=>'91','username'=>'游客34','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar9.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'7x3nQ','verification_token'=>'PGM6j3N_0cbJNnifrzNnUOnRgVC8QecO_1699342922','create_time'=>'1699342921','update_time'=>'1699342921','auth_key'=>'PiymAfU8x6qUQRboRy4lbQ2yMVdZHDvl','password_hash'=>'$2y$13$pWzuU5RHdPEXpByAJc9SrOZLNWja7v778rIA3wrGR1S8whM8rlzwq','password_reset_token'=>'D7zBkNyRPzp1sQ2ejxSGZCewgNHrvb6b_1699342922','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'35','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5AlNppNZIjfcaIQwmiYpHQs','store_id'=>'153','bloc_id'=>'91','username'=>'游客35','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar5.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'LwKYQ','verification_token'=>'PIo5owIrK_C-2TfFmAFhkUkL5CCJh-2z_1699454880','create_time'=>'1699454879','update_time'=>'1699454879','auth_key'=>'vnBiGNXKcbUy7YSHqqhCUyBFQZ5pWegd','password_hash'=>'$2y$13$Mz2no9s.8ciHT9oDCNNmPOjbLEjyRpWWentDTpDGpifAVVXep9NoW','password_reset_token'=>'-e8MHdUXg9b-c6M45C7P-G5p7j7QrAUz_1699454880','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'36','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5B5lG06Iq82QNrdDpc8CPfc','store_id'=>'153','bloc_id'=>'91','username'=>'游客36','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar10.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'jQX6w','verification_token'=>'Hvffqt9a8GqvvlJw-ZLMu_p4Mugy5YBt_1699518290','create_time'=>'1699518290','update_time'=>'1699518290','auth_key'=>'JTJmJZ0lrrbDRUXs2e4GEWo_wfnQEapg','password_hash'=>'$2y$13$Aagws5mxeN4JfJrOpnMk7eiVbjuUE7bYP0rcytyhNer5xTsk/8SkO','password_reset_token'=>'o5NUlqnXpP1daWenUw1eXlaq00SJFwJ5_1699518290','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'37','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5HlusfzuJtWxtJ_hbUEOzng','store_id'=>'153','bloc_id'=>'91','username'=>'游客37','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar5.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'5x0V2','verification_token'=>'yqQ6-lg0wxUzbu6s76IFpaGI-rs1uG4o_1699525275','create_time'=>'1699525275','update_time'=>'1699525275','auth_key'=>'-M4-TwGeQ8chwnVERuqwKDGIjJoEFOir','password_hash'=>'$2y$13$uaQj3yoePhfM1n00O0XVJum/YeaL2ZQlqhjbPdofsU2Q3ALmhCLY6','password_reset_token'=>'op9pWaWTy4_NFD1k0wNHGMFcbSesEFTt_1699525275','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'38','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5FoWpXkg4l9XMPaLWSVX2dE','store_id'=>'153','bloc_id'=>'91','username'=>'游客38','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar6.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'o2edw','verification_token'=>'34d_M9pXFaK5AgFChAuG4qm98IFVELpM_1699579118','create_time'=>'1699579117','update_time'=>'1699579117','auth_key'=>'Yj6c_p3GYEX-2kVHlEiPnH83zRUPECIH','password_hash'=>'$2y$13$Aevxqk0hwqBhxaq15hSnb.Br2KYeOdr7xtdpm40DBb0LB69C5kFCi','password_reset_token'=>'I5ukxUqj1-x3AOSeHdojBoJ1OSQePkL1_1699579118','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'39','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5FoWpXkg4l9XMPaLWSVX2dE','store_id'=>'153','bloc_id'=>'91','username'=>'游客38','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar3.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'yxjl2','verification_token'=>'UwResAlJwY1rFJvrxxABTTeDvdzn3umQ_1699579118','create_time'=>'1699579117','update_time'=>'1699579117','auth_key'=>'SQX0mDVCsBbHpg1rhexpE6_c0TtVO6Yw','password_hash'=>'$2y$13$Wc8/pfjehwXJYMBNfMqCvOyib7RFpI5jV5ZaS8O3VXJ7OnC1X465e','password_reset_token'=>'qIaeCm5_DZUQaglRvvym9QZ86Yqa5w5B_1699579118','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'40','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5KOgmknVunFwQt_A-z7ZyD8','store_id'=>'153','bloc_id'=>'91','username'=>'游客40','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar3.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'jQp5x','verification_token'=>'De-QiWhet_fyCdIfb_-IlD9-DdRcv-xW_1699685141','create_time'=>'1699685140','update_time'=>'1699685140','auth_key'=>'Vkyfue-J3ytWRFN5ROIaRJBVrLwcKEny','password_hash'=>'$2y$13$SmFe6N2nouZEEaea1g6IWeJAXxlzCFz/nQBPgyop3v/4ZnXJ8RoPW','password_reset_token'=>'69dlaJ3C8T7tGafCnKdcCd2q3gBJwblI_1699685141','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'41','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5KNq1HoPTOhhiSF7Mn5jmqo','store_id'=>'153','bloc_id'=>'91','username'=>'游客41','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar10.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'p2rdx','verification_token'=>'PveNVXCOX2X560PwPvQJ3n18hPHv_2Pe_1699838626','create_time'=>'1699838625','update_time'=>'1699838625','auth_key'=>'jmXYdSEgiP7EcdLDB98VaCgF3KcMV7BJ','password_hash'=>'$2y$13$VGczrJAw3wvvOHYOtBCQa.3f42T7uALzMp677DAhssw/ZAgzM2gta','password_reset_token'=>'2QxQmM24zgKE02xFEpjWZbuBNU6nJKdy_1699838626','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'42','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5H2Eamtphg4vNJqyGxzCLAQ','store_id'=>'153','bloc_id'=>'91','username'=>'游客42','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar1.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'rxOgx','verification_token'=>'L86lffzUAqe0FN7PpORolWe5ICFXGF9f_1699839793','create_time'=>'1699839793','update_time'=>'1699839793','auth_key'=>'2v1vYJntby86n-6sON1YKwzrtQMjj11q','password_hash'=>'$2y$13$5bNTFOqreYG74EQtMLu56.E9Km5RMkFYkTDXQBVM9u4pT5ROhddm2','password_reset_token'=>'aVFa4DLiw51yRwoYfCG2Emm0IPOndnhH_1699839793','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'43','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5BBtDtKU1DO8mt4CdIRRlEI','store_id'=>'153','bloc_id'=>'91','username'=>'游客43','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar4.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'yw7kw','verification_token'=>'nFouOlilI4gh3mbYN7jkwTloMc77q0jJ_1699840113','create_time'=>'1699840113','update_time'=>'1699840113','auth_key'=>'U5fMcfC2OUoBUK-xaUKQVJcWht9VDBY7','password_hash'=>'$2y$13$q322Y33NiWPmuyGuQ4.Qu.6tmpNAHG5JGLlGtVf7LU6a1wJoYOqN.','password_reset_token'=>'Lf7lPNG47mfAgaIpXSe66F87smLJCXdC_1699840113','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'44','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5LYJ8_4B9eZQVkvkJax12JM','store_id'=>'153','bloc_id'=>'91','username'=>'游客44','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar4.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'QLaqx','verification_token'=>'bvS6LViEuHKxxlJQfBRme4mfSVprBO6Y_1699841856','create_time'=>'1699841856','update_time'=>'1699841856','auth_key'=>'gPG-5EC5ybEYttXH2NSSaL9dbj7jgAZ4','password_hash'=>'$2y$13$J.OrBDB1I9ku2T9Nxab4/OQw/DYPE6TRXLTBQSr9UbaeIwc3HpMNa','password_reset_token'=>'5U95a1dltYf8i-uaD6SerpD9eERI7pih_1699841856','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'45','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5F3KcQ-HKd0Go1Mcdr0Oi-A','store_id'=>'153','bloc_id'=>'91','username'=>'游客45','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar2.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'2NYYw','verification_token'=>'LtIOqNDg33hFZzCbffyu78DpQ-qMr6de_1699869432','create_time'=>'1699869431','update_time'=>'1699869431','auth_key'=>'msHUY1bv5ELpfN8o0vwyZUGELJPGBBYJ','password_hash'=>'$2y$13$GxBHNT1ZyXijHVBMMRx5OOVLKRsYRVroe0/5pwruZUUri.TGNup4a','password_reset_token'=>'FY65MHV0qWV2Jd8t0a_5VbDlaIghAwYG_1699869432','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'46','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5PfKnoHLMJBtX1Jx-vW0z_0','store_id'=>'153','bloc_id'=>'91','username'=>'游客46','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar3.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'Qnez2','verification_token'=>'ROsHuZS9rTvp1SjArQ5G5R9rbV1uz5Co_1699892344','create_time'=>'1699892344','update_time'=>'1699892344','auth_key'=>'jv5ppXSt5SGoqIVs87ceBkc2WZ9pEURP','password_hash'=>'$2y$13$6VuDamKAg8DjV2racV7TR.gK9SeSGs3b5KX1bNSXszkiounMcj50S','password_reset_token'=>'NnqVMM7C5JRe2_KuP-31gczsT5hJakcR_1699892344','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'47','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5AflzE-ihz90y7hhA90wf3I','store_id'=>'153','bloc_id'=>'91','username'=>'游客47','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar10.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'wGWvw','verification_token'=>'p_Il3gHFnAnGhD0s3jx4k_WvCMMVejxF_1700031171','create_time'=>'1700031171','update_time'=>'1700031171','auth_key'=>'ChNjGkctpekcdUdcW6QwpZGm_dJcpXhZ','password_hash'=>'$2y$13$H3ix5MSSB.e2YRrAC.Vq1eg3WOUbJZEIi3FjEENi.a3rg1uQGSiFe','password_reset_token'=>'RPPqPcP011b3OgtqqxjES5WMBeZu7G6e_1700031171','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'48','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5CK1jCfFA-JIsiiJkkRvaUo','store_id'=>'153','bloc_id'=>'91','username'=>'游客48','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar3.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'2Wykx','verification_token'=>'gi_VGA_jpokzjLlfDGVyUiofa5ext4Y7_1700071232','create_time'=>'1700071231','update_time'=>'1700071231','auth_key'=>'x2wS3JHXppRBjjuGsHhWswatSNMhO_2Y','password_hash'=>'$2y$13$XvxdIO4/8pXEOf25ifHKcuXUEgB6Uwi0XMabiOVxcjBdovhdkk7w.','password_reset_token'=>'24_ZuR6GgBIhs5qS25Tpvb5ncRwNi1C3_1700071232','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'49','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5Jx8dkYl0Q0ni-wj2iFpISU','store_id'=>'153','bloc_id'=>'91','username'=>'游客49','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar10.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'2BO1Q','verification_token'=>'dKHMnf6CoAoNGsyFMLCWePNcKoTSqiEq_1700125645','create_time'=>'1700125644','update_time'=>'1700125644','auth_key'=>'txximBBL_wzk-SzJLxe3mcBhItl1qlIc','password_hash'=>'$2y$13$vZyGNwyYrpiQOgFWoAU19.ZnHuDhgWApTPC7K9t32w.yYwEFiZQQG','password_reset_token'=>'xtaKZ6a6Oi2BA4jDplsjRVU0ovjryzWX_1700125645','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'50','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5M4xNzUsHnswJAPIy3F-zmQ','store_id'=>'153','bloc_id'=>'91','username'=>'游客50','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar6.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'25pdw','verification_token'=>'pR3iQDQ2-m-xy8IwIEjq4qZAAb1XkUlU_1700128486','create_time'=>'1700128485','update_time'=>'1700128485','auth_key'=>'-Owv5VrlsqFvrcYwIauz3IjPX5rx69Ch','password_hash'=>'$2y$13$VF6F5.xrCaFq9YLbEJoijOm3/OPF5Bi3JyExeQI5jBiQFsFF9TVA6','password_reset_token'=>'hzchDcOx8dJWyr0QFYlfl-FZWezoP-SJ_1700128486','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'51','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5N8-0QRUrFzS8tjgRDTEaWs','store_id'=>'153','bloc_id'=>'91','username'=>'游客51','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar4.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'QmE4Q','verification_token'=>'z7ODYkxXOliBBILtOZPOMjaKXhnLpX3L_1700132649','create_time'=>'1700132648','update_time'=>'1700132648','auth_key'=>'DElyvy55vADxnyhO4lbuBVJLQTwY-_mz','password_hash'=>'$2y$13$dkqZFeKJvNcns/1S5qx9He0boElEX4JsCvbG0QY5TRrEvtuSwT1PW','password_reset_token'=>'S-uCtc2vtvBpdc3OoLhQp-4S3z8gVKjN_1700132649','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'52','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5K0I4F-3MjefDey8aOOHIN8','store_id'=>'153','bloc_id'=>'91','username'=>'游客52','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar2.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'wbGN2','verification_token'=>'7AE0YD297X5VsMUVkqM-kw89R50gQmT5_1700205258','create_time'=>'1700205257','update_time'=>'1700205257','auth_key'=>'rLsihh7lgNH6g95cLlwDgdQMDe-A33Tx','password_hash'=>'$2y$13$pSc.doasnJ.v6dooIqmxGePodtYQt6XOZZlKwnrgWAVQVt1i8txK.','password_reset_token'=>'rVw1SDJwl2FDRBfVwrUZJjrxOZith5LV_1700205258','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        $this->insert('{{%member}}',['member_id'=>'53','group_id'=>'1','level'=>'1','openid'=>'oJ8HC5Oxg3dj4yYyjKI9ke5gbWkk','store_id'=>'153','bloc_id'=>'91','username'=>'游客53','mobile'=>'','address'=>NULL,'nickName'=>'','avatarUrl'=>'public/avatar4.jpeg','gender'=>'0','country'=>'','province'=>'','status'=>'0','city'=>'','address_id'=>'0','invitation_code'=>'2vv42','verification_token'=>'4JwJ74QXnM6R61H_aJCZbYrQiNpoG3CI_1700209812','create_time'=>'1700209812','update_time'=>'1700209812','auth_key'=>'VHhdU8l6a-MpucXeW3HHF3A1MB1mIP07','password_hash'=>'$2y$13$H5pGGyUJEr4iOIakgA4GHO/LELDvC46ZdrRQDj9KZod731AJyLwUa','password_reset_token'=>'FbUlSbFy_UMS65Gz6SqQqXCZYS75PjgR_1700209812','realname'=>NULL,'avatar'=>NULL,'qq'=>NULL,'vip'=>NULL,'birthyear'=>NULL,'constellation'=>NULL,'zodiac'=>NULL,'telephone'=>NULL,'idcard'=>NULL,'studentid'=>NULL,'grade'=>NULL,'zipcode'=>NULL,'nationality'=>NULL,'resideprovince'=>NULL,'graduateschool'=>NULL,'company'=>NULL,'education'=>NULL,'occupation'=>NULL,'position'=>NULL,'revenue'=>NULL,'affectivestatus'=>NULL,'lookingfor'=>NULL,'bloodtype'=>NULL,'height'=>NULL,'weight'=>NULL,'alipay'=>NULL,'msn'=>NULL,'email'=>NULL,'taobao'=>NULL,'site'=>NULL,'bio'=>NULL,'interest'=>NULL,'organization_id'=>NULL]);
        
        /* 设置外键约束 */
        $this->execute('SET foreign_key_checks = 1;');
    }

    public function down()
    {
        $this->execute('SET foreign_key_checks = 0');
        /* 删除表 */
        $this->dropTable('{{%member}}');
        $this->execute('SET foreign_key_checks = 1;');
    }
}

